In [11]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity , pairwise_distances

In [16]:


model = SentenceTransformer('sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2')

sentences = [
    "Receta sin gluten para niños",
    "Postre apto para celíacos",
    "Alergia a la leche de vaca",
    "Bebida de almendra sin lactosa",
    "Alergia a los frutos secos",
    "Ensalada de frutas de temporada"
]




Loading weights: 100%|██████████| 199/199 [00:00<00:00, 6324.29it/s]


In [18]:
embeddings = model.encode(sentences, normalize_embeddings=True, convert_to_numpy=True, batch_size=32, show_progress_bar=True)
print(cosine_similarity(embeddings, embeddings))


Batches: 100%|██████████| 1/1 [00:00<00:00, 36.86it/s]

[[1.0000001  0.50776774 0.33050403 0.52990043 0.429698   0.4071425 ]
 [0.50776774 1.0000001  0.4151847  0.5799286  0.3941723  0.26869845]
 [0.33050403 0.4151847  1.0000002  0.5044599  0.53068864 0.17627698]
 [0.52990043 0.5799286  0.5044599  1.0000002  0.36331823 0.30599344]
 [0.429698   0.3941723  0.53068864 0.36331823 1.0000001  0.5952212 ]
 [0.4071425  0.26869845 0.17627698 0.30599344 0.5952212  1.0000002 ]]


In [14]:
l2_dist = pairwise_distances(embeddings, embeddings, metric='euclidean')
print(l2_dist)

[[0.        4.5570493 5.7889585 5.751327  6.2360196 5.031168 ]
 [4.5570493 0.        5.7481313 5.016884  5.5286226 6.392138 ]
 [5.7889585 5.7481313 0.        5.710508  6.351435  7.120403 ]
 [5.751327  5.016884  5.710508  0.        3.5669808 5.064651 ]
 [6.2360196 5.5286226 6.351435  3.5669808 0.        5.7460494]
 [5.031168  6.392138  7.120403  5.064651  5.7460494 0.       ]]
